export const individualGamesData = [
    {
        id: 0,
        title: 'Coinflip',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/coinflip.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 1,
        title: 'Crash',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/crash.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 2,
        title: 'Dice',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/dice.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 3,
        title: 'Lucky wheel',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/wheel.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 4,
        title: 'blackjack',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/BJ.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 5,
        title: 'rock paper scissors',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/RPS.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 6,
        title: 'minesweeper',
        description: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Individual/Minsweeper.svg',
        price: 254,
        type: 'individual',
    },
    {
        id: 7,
        title: 'Basic',
        description: 'Coin Flip, Dice, Rock Paper Scissors',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/basic.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 8,
        title: 'Medium 1',
        description: 'Wheel, Dice, Rock Paper Scissors',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/medium1.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 9,
        title: 'Medium 2',
        description: 'Crush, Dice, Rock Paper Scissors',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/medium2.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 10,
        title: 'Medium 3',
        description: 'Crush, Coin Flip, Rock Paper Scissors',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/medium3.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 11,
        title: 'Medium 4',
        description: 'Wheel, Coin Flip, Rock Paper Scissors',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/medium4.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 12,
        title: 'Medium 5',
        description: 'Wheel, Coin Flip, Dice',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/medium5.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 13,
        title: 'Medium 6',
        description: 'Crush, Coin Flip, Dice',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/medium6.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 14,
        title: 'Premium 1',
        description: 'Crush, Minesweeper, Wheel',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/premium1.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 15,
        title: 'Premium 2',
        description: 'Crush, Blackjack, Wheel',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/premium2.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 16,
        title: 'Premium 3',
        description: 'Blackjack, Minesweeper, Wheel',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/premium3.svg',
        price: 254,
        type: 'package',
    },
    {
        id: 17,
        title: 'Premium 4',
        description: 'Crush, Minesweeper, Blackjack',
        description2: 'Lorem ipsum dolor sit amet consectetur. Cras a in sit mauris. Amet odio vulputate.',
        imgUrl: './images/Packages/premium4.svg',
        price: 254,
        type: 'package',
    },
]